main/weston: fix build
This makes weston build again on x86_64. (It still won't build for
armhf and aarch64, because Alpine's mesa binary package is currently
stuck there, I'll look into that as well.) Detailed fixes:

1. New makedepends needed, because mesa-libwayland-egl does not exist
   anymore (see Alpine's aports commits 257a236 and 4f8b36b):
     wayland-libs-egl wayland-dev
   This fixes configure errors:

checking for EGL_TESTS... no
configure: error: Package requirements (egl glesv2 wayland-client wayland-egl) were not met:

Package 'wayland-client', required by 'virtual:world', not found
Package 'wayland-egl', required by 'virtual:world', not found

2. Disable RDP backend, because Weston source is incompatible with
   freerdp 2.0.0. This avoids compilation errors like this one:

libweston/compositor-rdp.c:193:5: error: 'SURFACE_BITS_COMMAND {aka struct _SURFACE_BITS_COMMAND}' has no member named 'bpp';